import 'package:x_express/Utils/exports.dart';
import '../Services/Promotion/promotion.dart';

List<SingleChildWidget> providers = [
  ChangeNotifierProvider(create: (_) => OrderServices()),
  ChangeNotifierProvider(create: (_) => Auth()),
  ChangeNotifierProvider(create: (_) => OrderDetailServices()),
  ChangeNotifierProvider(create: (_) => PromotionServices()),
  ChangeNotifierProvider(create: (_) => Language()),
  ChangeNotifierProvider(create: (_) => NotificationService()),
  ChangeNotifierProvider(create: (_) => NotificationListService()),
  ChangeNotifierProvider(create: (_) => ReSetPasswordService()),
  ChangeNotifierProvider(create: (_) => ReceiptService()),
  ChangeNotifierProvider(create: (_) => AddressService()),
  ChangeNotifierProvider(create: (_) => OrderStatusService()),
  ChangeNotifierProvider(create: (_) => PaymentOrderService()),
  ChangeNotifierProvider(create: (_) => ShipmentStatusService()),
  ChangeNotifierProvider(create: (_) => ShipmentServices()),
  ChangeNotifierProvider(create: (_) => ShipmentDetailServices()),
  ChangeNotifierProvider(create: (_) => CurrencyService()),
  ChangeNotifierProvider(create: (_) => DashboardService()),
  ChangeNotifierProvider(create: (_) => CurrencyTypeService()),
  ChangeNotifierProvider(create: (_) => ActivityService()),
  ChangeNotifierProvider(create: (_) => UserFormService()),
  ChangeNotifierProvider(create: (_) => CustomersService()),
  ChangeNotifierProvider(create: (_) => WarehouseService()),
  ChangeNotifierProvider(create: (_) => OpenOrderServices()),
  ChangeNotifierProvider(create: (_) => ReceiveServices()),
  ChangeNotifierProvider(create: (_) => ProfileService()),
  ChangeNotifierProvider(create: (_) => OrderUserServices()),
  ChangeNotifierProvider(create: (_) => SupplierService()),
  ChangeNotifierProvider(create: (_) => InventoryListDetailService()),
  ChangeNotifierProvider(create: (_) => ReceiveStatusService()),
  ChangeNotifierProvider(create: (_) => OnboardingService()),
  ChangeNotifierProvider(create: (_) => WebviewService()),
  ChangeNotifierProvider(create: (_) => DownloadService()),
  ChangeNotifierProvider(create: (_) => AgreementService()),
  ChangeNotifierProvider(create: (_) => LeadersService()),
  ChangeNotifierProvider(create: (_) => PromotionService()),
];
